CREATE DATABASE CERTIFICATEN
CREATE TABLE KLANTEN(
  ADD COLUMN KLANT_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  ADD COLUMN NAAM VARCHAR(200) NOT NULL,
  ADD COLUMN ORDER_ID INT(10)  NOT NULL;
  ADD FOREIGN KEY (ADRES_ID) REFERENCES ADRES(ADRES_ID)
);

CREATE TABLE ADRES(
  ADD COLUMN ADRES_ID  INT(10)  AUTO_INCREMENT PRIMARY KEY,
  ADD COLUMN STRAAT VARCHAR(200) UNSIGNED NOT NULL,
  ADD COLUMN NUMMER VARCHAR(200)  NOT NULL,
  ADD COLUMN POSTCODE VARCHAR(4)  NOT NULL,
  ADD COLUMN STAD VARCHAR(200)  NOT NULL
);

CREATE TABLE ORDERS(
  ADD COLUMN ORDER_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  ADD COLUMN  WORK_ORDER_NUMBER  VARCHAR(200) NOT NULL,
 ADD COLUMN PURCHASE_ORDER_NUMBER  VARCHAR(200) NOT NULL,
 ADD COLUMN SPECIFICATIE VARCHAR(200) NOT Null,
 ADD COLUMN TOTAAL_GEWICHT VARCHAR(200) NOT Null,
);

CREATE TABLE CERTIFICAAT(
  ADD COLUMN CERTIFICAAT_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  ADD COLUMN CERTIFICAAT_NUMBER VARCHAR(200) NOT NULL,
  ADD COLUMN DATUM_CERTIFICAAT DATE NOT NULL,
  ADD COLUMN SPECIFIEK_TONNAGE INT(200)
);

