CREATE TABLE KLANTEN(
  KLANT_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  NAAM VARCHAR(200) NOT NULL,
  ORDER_ID INT(10)  NOT NULL;
  FOREIGN KEY (ADRES_ID) REFERENCES ADRES(ADRES_ID),
);

CREATE TABLE ADRES(
  ADRES_ID  INT(10)  AUTO_INCREMENT PRIMARY KEY,
  STRAAT VARCHAR(200) UNSIGNED NOT NULL,
  NUMMER VARCHAR(200)  NOT NULL,
  POSTCODE VARCHAR(4)  NOT NULL,
  STAD VARCHAR(200)  NOT NULL
);

CREATE TABLE ORDERS(
  ORDER_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  WORK__ORDER_NUMBER  VARCHAR(200) NOT NULL,
 PURCHASE__ORDER_NUMBER  VARCHAR(200) NOT NULL,
 SPECIFICATIE VARCHAR(200) NOT Null,
 TOTAAL_GEWICHT VARCHAR(200) NOT Null,
);

CREATE TABLE CERTIFICAAT(
  CERTIFICAAT_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  CERTIFICAAT_NUMBER VARCHAR(200) NOT NULL,
  DATUM_CERTIFICAAT DATE NOT NULL,
  SPECIFIEK_TONNAGE INT(200)
);

