
CREATE TABLE KLANTEN(
  KLANT_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  NAAM VARCHAR(200) NOT NULL,
  STRAAT VARCHAR(200) NOT NULL,
  NUMMER VARCHAR(200) NOT NULL,
  POSTCODE VARCHAR(200) NOT NULL,
  STAD VARCHAR(200) NOT NULL,
  ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE ORDERS(
  ORDER_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
   WORK_ORDER_NUMBER  VARCHAR(200) NOT NULL,
 PURCHASE_ORDER_NUMBER  VARCHAR(200) NOT NULL,
 SPECIFICATIE VARCHAR(200) NOT Null,
 TOTAAL_GEWICHT VARCHAR(200) NOT Null,
   ADD FOREIGN KEY (CERTIFICAAT_ID) REFERENCES CERTIFICAAT(CERTIFICAAT_ID)
);

CREATE TABLE CERTIFICAAT(
  CERTIFICAAT_ID INT(10)  AUTO_INCREMENT PRIMARY KEY,
  CERTIFICAAT_NUMBER VARCHAR(200) NOT NULL,
  DATUM_CERTIFICAAT DATE NOT NULL,
  SPECIFIEK_TONNAGE INT(200)
);

